routes/web.php
<?php 
Route::get('/subject/{subject}/{category?}','PostController@listBySubject')->name('posts.category.index');
Route::redirect('/','/home');
Route::get('/home','HomeController@index')->name('home');
Route::get('archives/{year}/{month}','PostController@getByArchive')->name('archives');
Route::group(['namespace' => 'Auth'],function(){
	Route::group(['middleware' => 'guest'],function(){
		Route::get('/user/token','AuthTokenController@getToken')->name('token');
		Route::get('/token/resend','AuthTokenController@getResend')->name('resend-token');
		Route::post('/user/token','AuthTokenController@postToken')->name('token');
		Route::get('/register',[
			'uses' => 'RegisterController@getRegister',
			'as' => 'register'
		]);
		Route::post('/register',[
			'uses' => 'RegisterController@postRegister',
			'as' => 'register'
		]);
		Route::get('/login',[
			'uses' => 'LoginController@getLogin',
			'as' => 'login'
		]);
		Route::post('/login',[
			'uses' => 'LoginController@postLogin',
			'as' => 'login'
		]);
	
		

		Route::get('/activate/{email}/{token}','EmailActivationController@activateUser');
		Route::get('/resetpassword','ForgotPasswordController@getForgotPassword')->name('reset');
		Route::post('/resetpassword','ForgotPasswordController@postForgotPassword')->name('reset');
		Route::get('/reset/{email}/{token}','ResetPasswordController@getPasswordResetThroughEmail')->name('reset-password');
		Route::post('/reset-password','ResetPasswordController@postPasswordResetThroughEmail')->name('reset-password');
		Route::get('/resetBySecurityQuestion' , ['uses' => 'ResetPasswordController@getPasswordResetThroughQuestion','as' => 'reset.security']);
		Route::post('/resetBySecurityQuestion/stage1' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion1','as' => 'reset.security1']);
		Route::post('/resetBySecurityQuestion/stage2' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion2','as' => 'reset.security2']);
		Route::post('/resetBySecurityQuestion/stage3' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion3','as' => 'reset.security3']);
	});
});

// middleware
Route::group(['middleware' => 'user'],function(){
	Route::get('/dashboard','UserController@dashboard')->name('user.dashboard');
	Route::get('/profile/{username}',['uses' => 'UserController@getProfile','as' =>'profile']);
	Route::get('/profile/{username}/viewas',['uses' => 'UserController@getProfile','as' =>'profile.viewas']);
	Route::post('/profile',['uses' => 'UserController@postProfile','as' => 'profile']);
	Route::post('/rate/{username}',['uses' => 'UserController@postRate','as' => 'rating']);
		Route::post('/change-password',[
		'uses' => 'Auth\ChangePasswordController@postChangePassword',
		'as' => 'change-password'
	]);
	Route::get('/change-password',[
		'uses' => 'Auth\ChangePasswordController@getChangePassword',
		'as' => 'change-password'
	]);
	Route::post('logout',[
		'uses' => 'Auth\LoginController@logout',
		'as' => 'logout',
	]);	
	Route::post('/comments/{post}','CommentController@store')->name('comments.store');
	Route::put('/comments/{comment}','CommentController@update')->name('comments.update');
	Route::delete('/comments/{comment}','CommentController@destroy')->name('comments.destroy');
	Route::get('/replies/{reply}/{post}','RepliesController@edit')->name('replies.edit');
	Route::post('/replies/{comment}/{post}','RepliesController@store')->name('replies.store');
	Route::put('/replies/{reply}/{comment}/{post}','RepliesController@update')->name('replies.update');
	Route::delete('/replies/{reply}','RepliesController@destroy')->name('replies.destroy');
	Route::get('/comments/{comment}/{post}','CommentController@edit')->name('comments.edit');
	Route::post('/download/{post}','PostController@downloadFile')->name('posts.download');
	Route::get('/settings/twofactor','TwoFactorSettingsController@index')->name('2fa-settings');
	Route::put('/settings/twofactor','TwoFactorSettingsController@update');

	Route::post('/like/{type}/{id}',[
		'uses' => 'LikeController@like',
		'as'	=> 'like'
	]);
	Route::post('/dislike/{type}/{id}',[
		'uses' => 'LikeController@dislike',
		'as'	=> 'dislike'
	]);
	Route::post('/reset/like/{type}/{id}',[
		'uses' => 'LikeController@reset',
		'as'	=> 'reset-like'
	]);




	Route::get('/markAsRead',function(){
		\Sentinel::getUser()->unreadNotifications->markAsRead();
	});
});
	Route::group(['middleware' => 'admin'],function(){
		Route::view('/admin','admin.dashboard');
		Route::resource('/posts','PostController');
		Route::get('/upgrade','AdminController@listUsers')->name('list.users');
		Route::get('/downgrade','AdminController@listUsers');
		Route::post('/downgrade/{username}','AdminController@downgradeUser')->name('downgrade.users');
		Route::post('/upgrade/{username}','AdminController@upgradeUser')->name('upgrade.users');
		Route::get('/unapproved',['uses' => 'PostController@unApproved','as' => 'posts.unapproved']);
		Route::post('/posts/approve/{id}',['uses' => 'AdminController@approvePost','as' =>'posts.approve']);
		Route::resource('/tags','TagController');
		Route::get('/popular/tags','TagController@sortByPopularity');
		Route::put('/approve/comments/{comment}','CommentController@approveComment')->name('comments.approve');
		Route::put('/approve/replies/{reply}','RepliesController@approveReply')->name('replies.approve');
	});
	
	Route::get('/posts','PostController@index')->name('posts.index');
	Route::get('/posts/{post}','PostController@show')->name('posts.show');
	Route::get('/tags/{tag}','TagController@show')->name('tags.show');
Route::get('/comments/{comment}','CommentController@show')->name('comments.show');
Route::get('/replies/{reply}','RepliesController@show')->name('replies.show');
Route::get('/test',function(){
	dd(\App\Hint::menuElements());
	dd(array_merge(request()->all(),['reply' => Route::current()->parameter('reply')]));
	dd(request()->route('reply'));
	dd(Route::input('reply'));
	dd(request()->route()->parameter('reply'));
	$user = Sentinel::findById(10);
	$post = \App\Post::find(5);
	foreach ($post->RecentPostsDependingOnBranch($user->year,$user->department) as $posts) {
		dd($posts);
		foreach ($posts as $post) {
			echo $post->title . '<hr/>';
		}
	}
	//dd(\App\Post::find(5)->hints->first()->);	
});
?>

app/Reply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    protected $table = 'replies';
    protected $fillable = ['body','edited_body','approved','approved_by','approved_at'];
    public function getCreatedAtAttribute($value){

        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$value)->diffForHumans();
    }
    public function getUpdatedAtAttribute($value){

        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$value)->diffForHumans();
    }
    public function comment(){
        return $this->belongsTo(Comment::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
      
    public function editor(){
        return $this->belongsTo(User::class,'edited_by','id');
    }
    public function post(){
        return $this->belongsTo(Post::class);
    }
     public function likes(){
      return$this->morphMany(Like::class,'likable');
   }
}

app/Tag.php
<?php

namespace App;
use Sentinel;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    protected $fillable = ['name','admin_id'];
    private static $delimeters = [' ',','];
    public function getRouteKeyName(){
        return 'name';
    }
   
    public function posts(){
        return $this->belongsToMany(Post::class);
    }
    public function admin(){
        return $this->belongsTo(Admin::class);
    }
    public static function delimeters($request){
        foreach (self::$delimeters as $delimeter) {
            if(strpos($request,$delimeter)){
                $delimeters[] = $delimeter;    
            } 
        }
        return $delimeters ?? NULL;
    }
     public static function assignTags($new)
    {
        $tags = new self();
        if(self::delimeters($new) != NULL){
            $inserted_tags = preg_split('/(,| )/',$new);
                $counter = 0;
           foreach ($inserted_tags as $tag) {
               if($tags->where('name',str_slug($tag))->exists()){
                    $user_tags[] = Tag::whereName(['name' => $tag])->get();
                    continue;
               }
               $tags->create(['name' => str_slug($tag) , 'admin_id' => Sentinel::getUser()->id]);
               $user_tags[] = Tag::whereName($tag)->get();
               ++$counter;
           }
         
         
        }else{
            if(!$tags->where('name',str_slug($new))->exists()){
                $tags->create(['name' => str_slug($new),'admin_id' => Sentinel::getUser()->id]);
                
            }            
            $user_tags = $tags->where('name',str_slug($new))->first();

        }
        \Session::put('tags',$user_tags);
        return true;
    }
    public static function PopularTags()
    {
        return static::join('post_tag','post_tag.tag_id', '=' , 'tags.id')
        ->groupBy(['tags.id','tags.name'])
        ->get(['tags.id','tags.name',\DB::raw(' count(tags.id) as tag_count')])
        ->sortByDesc('tag_count')->take(3);
    }
    public static function countTag($tag){
        return static::whereName($tag)->count();
    }
   
}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Sentinel;
use Illuminate\Http\Request;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       return view('tags.index')->with('tags',Tag::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store()
    {
       request()->validate([
            'name' => 'required|unique:tags,name'
        ]);
       Tag::create(['name' => request('name') , 'admin_id' => Sentinel::getUser()->id]);
       return redirect()->route('tags.index')->with('success','Tag Created !');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag) //find()
    {
        return view('tags.show')->with('tag',$tag);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.edit')->with('tag',$tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Tag $tag)
    {
        request()->validate([
            'name' => "required|unique:tags,name,$tag->id|string|min:3|max:32"
        ]);
        $tag->update(['name' => request('name') , 'admin_id' => Sentinel::getUser()->id]);
        return redirect()->route('tags.index')->with('success','Tag Edited !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();
        return redirect()->route('tags.index')->with('success','Tag Deleted !');
    }
    public function sortByPopularity(){
        return view('tags.index')->with('tags',Tag::PopularTags());
    }
}

resources/views/tags/create.blade.php
@extends('layouts.app')

@section('panel-heading')
    Create A Tag
@endsection
@section('content')
  <form action="{{ route('tags.store') }}" method="POST">
        {{csrf_field()}}
        <div class="form-group">
            <label for="title"> Name</label>
            <input type="text" name="name" class="form-control" placeholder="name" value="{{ old('name')}}">
        </div>
        
        <div class="form-group">
            <input type="submit" value="Release Tag" class="btn btn-primary">
        </div>
  </form>
 

@endsection

resources/views/tags/edit.blade.php
@extends('layouts.app')

@section('panel-heading')
    Edit A Tag
@endsection
@section('content')
  <form action="{{  route('tags.update',$tag->name) }}" method="POST" >
        {{csrf_field()}}

         <div class="form-group">
            <label for="Tags"> Tag Name</label>
            <input type="text" name="name" class="form-control" placeholder="Edit Tag Name" value="{{ $tag->name }}">
        </div>
       

        <div class="form-group">
            <input type="hidden" name="_method" value="PUT">
            <input type="submit" value="Edit Tag" class="btn btn-primary">
        </div>
  </form>
 

@endsection

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('panel-heading')
	Tags
@endsection

@section('content')
	@if (count($tags) > 0)
		<ul class="list-group">
		@foreach ($tags as $tag)
		<li class="list-group-item"><a href="{{ route('tags.show',$tag->name) }}">{{ $tag->name }}</a></li>
		@endforeach
			
		</ul>
	@endif
@endsection

resources/views/tags/show.blade.php
@extends('layouts.app')
@section('style')
 
<link href="{{ asset('css/comment.css') }}" rel="stylesheet">

@endsection
@section('panel-heading')
	<p class="text-center">{{ $tag->posts->count() . ' Posts have ' . strtoupper($tag->name) . ' Tag'}}</p>
@endsection

@section('content')
	@if (count($tag->posts) > 0)
		@foreach ($tag->posts()->where('approved',1)->get() as $post)
		<div class="row">
			
				 <div class="panel panel-white post panel-shadow">
		            <div class="post-heading">
		               <div class="pull-left image"> 
		                  <img src=" {{ asset($post->admin->profile_picture  ?? 'default.png') }}" class="img-circle avatar" alt="user profile image" style="max-width: 50px;max-height: 50px;border-radius: 50%">
		               </div>
		               <div class="pull-left meta">
		                  <div class="title h5">
		                     <a href="/profile/{{ $post->admin->username }}"><b>{{ $post->admin->first_name . ' ' . $post->admin->last_name }}</b></a>
		                     created a post
		                     <p> <small>{{ $post->admin->roles->first()->slug }}</small></p>
		                  </div>
		                  <h6 class="text-muted time"> {{ $post->created_at }}</h6>
		               </div>
		            </div>
		      </div>

		      <div class="post-description"> {{-- post-description --}}
		      	<p>   {{ $post->body }}</p> 
		        </div>
		</div>

<hr>
		@endforeach
			
	@endif
@endsection