routes/web.php
<?php 
Route::get('/subject/{subject}/{category?}','PostController@listBySubject')->name('posts.category.index');
Route::redirect('/','/home');
Route::get('/home','HomeController@index')->name('home');
Route::get('archives/{year}/{month}','PostController@getByArchive')->name('archives');
Route::group(['namespace' => 'Auth'],function(){
	Route::group(['middleware' => 'guest'],function(){
		Route::get('/user/token','AuthTokenController@getToken')->name('token');
		Route::get('/token/resend','AuthTokenController@getResend')->name('resend-token');
		Route::post('/user/token','AuthTokenController@postToken')->name('token');
		Route::get('/register',[
			'uses' => 'RegisterController@getRegister',
			'as' => 'register'
		]);
		Route::post('/register',[
			'uses' => 'RegisterController@postRegister',
			'as' => 'register'
		]);
		Route::get('/login',[
			'uses' => 'LoginController@getLogin',
			'as' => 'login'
		]);
		Route::post('/login',[
			'uses' => 'LoginController@postLogin',
			'as' => 'login'
		]);
	
		

		Route::get('/activate/{email}/{token}','EmailActivationController@activateUser');
		Route::get('/resetpassword','ForgotPasswordController@getForgotPassword')->name('reset');
		Route::post('/resetpassword','ForgotPasswordController@postForgotPassword')->name('reset');
		Route::get('/reset/{email}/{token}','ResetPasswordController@getPasswordResetThroughEmail')->name('reset-password');
		Route::post('/reset-password','ResetPasswordController@postPasswordResetThroughEmail')->name('reset-password');
		Route::get('/resetBySecurityQuestion' , ['uses' => 'ResetPasswordController@getPasswordResetThroughQuestion','as' => 'reset.security']);
		Route::post('/resetBySecurityQuestion/stage1' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion1','as' => 'reset.security1']);
		Route::post('/resetBySecurityQuestion/stage2' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion2','as' => 'reset.security2']);
		Route::post('/resetBySecurityQuestion/stage3' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion3','as' => 'reset.security3']);
	});
});

// middleware
Route::group(['middleware' => 'user'],function(){
	Route::get('/dashboard','UserController@dashboard')->name('user.dashboard');
	Route::get('/profile/{username}',['uses' => 'UserController@getProfile','as' =>'profile']);
	Route::get('/profile/{username}/viewas',['uses' => 'UserController@getProfile','as' =>'profile.viewas']);
	Route::post('/profile',['uses' => 'UserController@postProfile','as' => 'profile']);
	Route::post('/rate/{username}',['uses' => 'UserController@postRate','as' => 'rating']);
		Route::post('/change-password',[
		'uses' => 'Auth\ChangePasswordController@postChangePassword',
		'as' => 'change-password'
	]);
	Route::get('/change-password',[
		'uses' => 'Auth\ChangePasswordController@getChangePassword',
		'as' => 'change-password'
	]);
	Route::post('logout',[
		'uses' => 'Auth\LoginController@logout',
		'as' => 'logout',
	]);	
	Route::post('/comments/{post}','CommentController@store')->name('comments.store');
	Route::put('/comments/{comment}','CommentController@update')->name('comments.update');
	Route::delete('/comments/{comment}','CommentController@destroy')->name('comments.destroy');
	Route::get('/replies/{reply}/{post}','RepliesController@edit')->name('replies.edit');
	Route::post('/replies/{comment}/{post}','RepliesController@store')->name('replies.store');
	Route::put('/replies/{reply}/{comment}/{post}','RepliesController@update')->name('replies.update');
	Route::delete('/replies/{reply}','RepliesController@destroy')->name('replies.destroy');
	Route::get('/comments/{comment}/{post}','CommentController@edit')->name('comments.edit');
	Route::post('/download/{post}','PostController@downloadFile')->name('posts.download');
	Route::get('/settings/twofactor','TwoFactorSettingsController@index')->name('2fa-settings');
	Route::put('/settings/twofactor','TwoFactorSettingsController@update');

	Route::post('/like/{type}/{id}',[
		'uses' => 'LikeController@like',
		'as'	=> 'like'
	]);
	Route::post('/dislike/{type}/{id}',[
		'uses' => 'LikeController@dislike',
		'as'	=> 'dislike'
	]);
	Route::post('/reset/like/{type}/{id}',[
		'uses' => 'LikeController@reset',
		'as'	=> 'reset-like'
	]);




	Route::get('/markAsRead',function(){
		\Sentinel::getUser()->unreadNotifications->markAsRead();
	});
});
	Route::group(['middleware' => 'admin'],function(){
		Route::view('/admin','admin.dashboard');
		Route::resource('/posts','PostController');
		Route::get('/upgrade','AdminController@listUsers')->name('list.users');
		Route::get('/downgrade','AdminController@listUsers');
		Route::post('/downgrade/{username}','AdminController@downgradeUser')->name('downgrade.users');
		Route::post('/upgrade/{username}','AdminController@upgradeUser')->name('upgrade.users');
		Route::get('/unapproved',['uses' => 'PostController@unApproved','as' => 'posts.unapproved']);
		Route::post('/posts/approve/{id}',['uses' => 'AdminController@approvePost','as' =>'posts.approve']);
		Route::resource('/tags','TagController');
		Route::get('/popular/tags','TagController@sortByPopularity');
		Route::put('/approve/comments/{comment}','CommentController@approveComment')->name('comments.approve');
		Route::put('/approve/replies/{reply}','RepliesController@approveReply')->name('replies.approve');
	});
	
	Route::get('/posts','PostController@index')->name('posts.index');
	Route::get('/posts/{post}','PostController@show')->name('posts.show');
	Route::get('/tags/{tag}','TagController@show')->name('tags.show');
Route::get('/comments/{comment}','CommentController@show')->name('comments.show');
Route::get('/replies/{reply}','RepliesController@show')->name('replies.show');
Route::get('/test',function(){
	dd(\App\Hint::menuElements());
	dd(array_merge(request()->all(),['reply' => Route::current()->parameter('reply')]));
	dd(request()->route('reply'));
	dd(Route::input('reply'));
	dd(request()->route()->parameter('reply'));
	$user = Sentinel::findById(10);
	$post = \App\Post::find(5);
	foreach ($post->RecentPostsDependingOnBranch($user->year,$user->department) as $posts) {
		dd($posts);
		foreach ($posts as $post) {
			echo $post->title . '<hr/>';
		}
	}
	//dd(\App\Post::find(5)->hints->first()->);	
});
?>

app/Reply.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reply extends Model
{
    protected $table = 'replies';
    protected $fillable = ['body','edited_body','approved','approved_by','approved_at'];
    public function getCreatedAtAttribute($value){

        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$value)->diffForHumans();
    }
    public function getUpdatedAtAttribute($value){

        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$value)->diffForHumans();
    }
    public function comment(){
        return $this->belongsTo(Comment::class);
    }
    public function user(){
        return $this->belongsTo(User::class);
    }
      
    public function editor(){
        return $this->belongsTo(User::class,'edited_by','id');
    }
    public function post(){
        return $this->belongsTo(Post::class);
    }
     public function likes(){
      return$this->morphMany(Like::class,'likable');
   }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use App\Post;
use Sentinel;
use Carbon\Carbon;

class PostController extends Controller
{

   private $uploads = ['images'=>'imagePath','pdf' => 'pdfPath'];
  
    public static function listBySubject($subject,$category = null){
        $validator = \Validator::make([
            'subject' => $subject,
            'category' => $category
        ],[
            'subject' => 'required|min:5|max:15|exists:posts,subject',
            'category' => 'nullable|in:section,midterm,final,lecture'
        ]);
        if($validator->fails()){
            return redirect()->home()->withErrors($validator);
        }
        $posts = Post::listBySubject($subject,$category);
        if($posts->count()){
            return view('posts.index',compact('posts'));
        }
        return redirect()->route('posts.index')->with('error','No such subject nor category');

    }
   
    public function unApproved(){
        $posts = Post::listUnApproved();
        return view('posts.index')->with(['posts' => $posts]);
    }
    public function getByArchive(){
        $posts = Post::listApproved()->filter(request()->route('month'),request()->route('year'))->get();
        return view('posts.index',compact('posts'));
    }
    public function index()
    {
        $posts = Post::listApproved()->get();    
        return view('posts.index')->with('posts',$posts);
    }

 
    public function create()
    {
        return view('posts.create');
    }

    public function store()
    {

      
        $data = request()->validate([
            'title' => 'required|string|unique:posts,title|min:3|max:32',
            'body' => [
                'required','string','regex:/^[a-zA-Z0-9-_. ]*$/','min:6','max:300'
            ],
            'imagePath' => 'image|nullable|max:1999',
            'pdfPath' => 'max:10000|nullable',
            'edu_year' => 'required|in:Preparatory_Year,First_Year,Second_Year,Third_Year,Fourth_Year',
            'term' => 'required|string|in:first_term,second_term',
            'category' => 'required|string|in:section,mid-term,final,lecture',
            'subject' => new \App\Rules\SubjectValidation(request('term'),request('edu_year')),
            'department' =>  new \App\Rules\DepartmentValidation(request('term'),request('edu_year')),
            'tags'  => [
                'required','regex:/^[a-zA-Z0-9-_. ]*$/','min:3','max:32','string'
            ],
        ]);
        $now = \Carbon\Carbon::now();
       

       	$data['admin_id'] = Sentinel::getUser()->id;
       	$data['created_at'] = date('Y-m-d H:i:s');
       	$data['updated_at'] = null;
        if (Sentinel::getUser()->hasAccess('admin.create')) {
            $data['approved'] = 1;
            $data['approved_by'] = Sentinel::getUser()->username;
            $data['approved_at'] = date('Y-m-d H:i:s');
        }
        if(\App\Tag::assignTags(request('tags'))){
            $post = Post::create($data);
        }
        if(is_array(\Session::get('tags'))){
            foreach (\Session::get('tags') as $tag) {
                $post->tags()->attach($tag);
            }
        }else{
            $post->tags()->attach(\Session::get('tags'));
        }
         
        \Session::forget('tags');
        foreach ($this->uploads as $key => $upload) {
            if(request()->hasFile($upload)){
                $file_with_ext = request()->file($upload)->getClientOriginalName();
                $file_ext = request()->file($upload)->getClientOriginalExtension();
                $file_name_new = sha1(str_random(40). time() ) . '.' . $file_ext;
                $path = request()->file($upload)->move(public_path() ."/$key/",$file_name_new);
                // $path->getPath();
                Post::whereTitle(request('title'))->update([$upload => $file_name_new]);
            }
            continue;
        }
        return redirect()->route('posts.index')->with('success','Post Created');
    }

    
    public function show(Post $post) 
    {
        if($post->approved === 1){
            $like = new \App\Like;
        
            return view('posts.show')->with(['post'=> $post , 'like' => $like]);

        }
        return redirect()->route('posts.index')->with('error','Post Is not approved yet to be shown');
        
      
    }

    public function edit(Post $post)
    {
        if($post->approved === 1){
            $like = new \App\Like;
        
            if(Sentinel::getUser()->id != $post->admin_id && Sentinel::getUser()->hasAccess('moderator.edit')){
                return redirect()->route('posts.index')->with('error','Unauthorized Page');
            }
            return view('posts.edit')->with(['post'=> $post , 'like' => $like]);

        }
        return redirect()->route('posts.index')->with('error','Post Is not approved yet to be shown');
      
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  request()
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Post $post){
      
    	$data = request()->validate([
            'title' => "required|string|unique:posts,title,$post->id|min:3|max:32",
            'body' => [
                'required','string','regex:/^[a-zA-Z0-9-_.\'\" ]*$/','min:6','max:300'
            ],
            'imagePath' => 'image|nullable|max:1999',
            'pdfPath' => 'max:10000|nullable',
            'edu_year' => 'required|in:Preparatory_Year,First_Year,Second_Year,Third_Year,Fourth_Year',
            'term' => 'required|in:first_term,second_term',
            'category' => 'required|string|in:section,mid-term,final,lecture',
            'subject' => new \App\Rules\SubjectValidation(request('term'),request('edu_year')),
            'department' => new \App\Rules\DepartmentValidation(request('term'),request('edu_year')),
            'tags'  => [
                'nullable','regex:/^[a-zA-Z0-9-_. ]*$/','min:3','max:32','string'
            ],
        ]);
       	$data['edited_by'] = Sentinel::getUser()->id;
       	$data['updated_at'] = date('Y-m-d H:i:s');
      	$data = array_except($data, 'tags');

       if($post->update($data)){
            
            if(!empty(request('tags')) && \App\Tag::assignTags(request('tags'))){
                if(is_array(\Session::get('tags'))){
                    for ($i = 0; $i < count(\Session::get('tags')); $i++) {
                        if($i == 0){
                            $post->tags()->sync(\Session::get('tags')[$i]);
                            continue;
                        }
                        $post->tags()->sync(\Session::get('tags')[$i],false);
                    }
                }else{
                    $post->tags()->sync(\Session::get('tags'),true);
                }
                \Session::forget('tags');
            }
            foreach ($this->uploads as $key => $upload) {
                if(request()->hasFile($upload)){
                    $file_ext = request()->file($upload)->getClientOriginalExtension();
                    $file_name_new = sha1(str_random(40). time() ) . '.' . $file_ext;
                    $path = request()->file($upload)->move(public_path() ."/$key/",$file_name_new);
                    Post::whereTitle($post->title)->update([$upload => $file_name_new]);
                }
                continue;
            }
               
            return redirect('/posts')->with('success','Post Updated');

        }     
        return redirect()->route('posts.index')->with('error','Could not Update Post');
    }

    public function destroy(Post $post)
    {
        if(Sentinel::getUser()->id != $post->admin_id && Sentinel::getUser()->hasAccess('moderator.delete')){
            return redirect('/posts')->with('error','Unauthorized Page');
        }
        if($post->imagePath !== NULL)
        \File::delete('images/'.$post->imagePath);
        $post->delete();
        return redirect('/posts')->with('success','Post deleted');
    }

    public function downloadFile(Post $post)
    {
        if($post->exists()){
            if(\File::exists(public_path(). '/pdf/'. $post->pdfPath)){
                return response()->download(public_path() . '/pdf/'. $post->pdfPath,$post->pdfPath,['Content-Type' => 'application/pdf','Content-Description' => 'File Transfer','Content-Length' => filesize(public_path() . '/pdf/'. $post->pdfPath)]);
            }
            return back()->with('error','File Does not exist');
        }
        return back()->with('error','Invalid Record');

    }   
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('panel-heading')
    Create A Post
@endsection
@section('content')
  <form action="{{ route('posts.store') }}" method="POST" enctype='multipart/form-data'>
        {{csrf_field()}}
        <div class="form-group">
            <label for="title"> Title</label>
            <input type="text" name="title" class="form-control" placeholder="title" value="{{ old('title')}}">
        </div>
        <div class="form-group">
            <label for="body">Post Body</label>
            <textarea name="body" id="article-ckeditor" class="form-control" placeholder="Body Text"> {{ old('body')}}</textarea>
        </div>
        <div class="form-group">
              <label for="department"> Department</label>
            <select class="form-control" name="department">
              <option selected disabled>Pick Up A Department</option>
                <option value="electronics_and_communication">Electronics & Communication</option>
              <option value="civil">Civil</option>
              <option value="electrical_power">Electrial Power</option>
              <option value="bio_medical">Bio Medical</option>
              <option value="chemical"> Chemical </option>
              <option value="architecture">Architecture</option>
            </select>
        </div>
      
    
        <div class="form-group">
        <label for="year">Education Year</label>
            <select class="form-control" name="edu_year">
              <option selected disabled>Pick Up A Year</option>
                <option value="Preparatory_Year">Preparatory Year</option>
                <option value="First_Year">First Year</option>
              <option value="Second_Year">Second Year</option>
              <option value="Third_Year">Third Year</option>
              <option value="Fourth">Fourth Year</option>
            </select>
        </div>
        <div class="form-group">
            <label for="image"> Upload an Image For Post</label>
            <input type="file" name="imagePath">
        </div>
         <div class="form-group">
            <label for="pdf">Upload a PDF for post</label>
            <input type="file" name="pdfPath">
        </div>
          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" name="category">
              <option selected disabled>Pick Up A Category</option>
              <option value="section">Section</option>
              <option value="lecture">Lecture</option>
              <option value="final">Final Exam</option>
              <option value="midterm">Mid Term Exam</option>
            </select>
        </div>
         <div class="form-group">
            <label for="category">subject</label>
            <select class="form-control" name="subject">
              <option selected disabled>Pick Up A Category</option>
              <option value="math2">Math(2)</option>
              <option value="electronics2">electronics</option>
            </select>
        </div>
        <div class="form-group">
            <label for="term">Term</label>
            <select class="form-control" name="term">
              <option selected disabled>Pick Up A Term</option>
              <option value="first_term">First Term</option>
              <option value="second_term">Second Term</option>
            </select>
        </div>
        <div class="form-group">
            <label for="tags">Tag</label>
            <input type="text" name="tags" class="form-control">
        </div>

        <div class="form-group">
            <input type="submit" value="Release Post" class="btn btn-primary">
        </div>
  </form>
 

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('panel-heading')
    Edit A Post
@endsection
@section('content')
  <form action="{{  route('posts.update',$post->title) }}" method="POST" enctype="multipart/form-data">
        {{csrf_field()}}
         <div class="form-group">
            <label for="title"> Title</label>
            <input type="text" name="title" class="form-control" placeholder="title" value="{{ $post->title }}">
        </div>
        <div class="form-group">
            <label for="body">Post Body</label>
            <textarea name="body" id="article-ckeditor" class="form-control" placeholder="Body Text"> {{ $post->body }}</textarea>
        </div>
        
        <div class="form-group">
              <label for="department"> Department</label>
            <select class="form-control" name="department">        
              <option selected disabled>Pick Up A Department</option>
                <option value="electronics_and_communication" {{ ($post->department === "electronics_and_communication") ? "selected" : ''}}>Electronics & Communication</option>
              <option value="civil" {{ ($post->department === "civil") ? "selected" : ''}} >Civil</option>
              <option value="electrical_power" {{ ( $post->department === "electrical_power") ? "selected" : ''}}>Electrial Power</option>
              <option value="bio_medical" {{ ( $post->department === "bio_medical") ? "selected" : ''}} >Bio Medical</option>
              <option value="chemistry" {{ ($post->department === "chemistry") ? "selected" : ''}} > Chemistry </option>
              <option value="architecture" {{ ( $post->department === "architecture") ? "selected" : ''}} >Architecture</option>
            </select>
        </div>
 
        <div class="form-group">
        <label for="year">Education Year</label> 
            <select class="form-control" name="edu_year">
              <option selected disabled>Pick Up A Year</option>
                <option value="Preparatory_Year" {{ ( $post->edu_year === "Preparatory_Year") ? "selected" : ''}}>Preparatory Year</option>
                <option value="First_Year" {{ (  $post->edu_year === "First_Year") ? "selected" : ''}}>First Year</option>
              <option value="Second_Year" {{ ( $post->edu_year === "Second_Year") ? "selected" : ''}}>Second Year</option>
              <option value="Third_Year" {{ (  $post->edu_year === "Third_Year") ? "selected" : ''}}>Third Year</option>
              <option value="Fourth_Year" {{ (  $post->edu_year === "Fourth_Year") ? "selected" : ''}}>Forth Year</option>
            </select>
        </div>

        <div class="form-group">
            <label for="image"> Upload an Image For Post</label>
            <input type="file" name="imagePath">
        </div>

         <div class="form-group">
            <label for="pdf">Upload a PDF for post</label>
            <input type="file" name="pdfPath">
        </div>

          <div class="form-group">
            <label for="category">Category</label>
            <select class="form-control" name="category">
              <option selected disabled>Pick Up A Category</option>
              <option value="section" {{ $post->category === "section" ? "selected" :""  }}>Section</option>
              <option value="lecture" {{ $post->category === "lecture" ? "selected" :""  }}>Lecture</option>
              <option value="final" {{ $post->category === "final" ? "selected" :""  }}>Final Exam</option>
              <option value="mid-term" {{ $post->category === "mid-term" ? "selected" :""  }}>Mid Term Exam</option>
             </select>
        </div>
          @php
            $hint = $post->hints()->where('term',$post->term)->first();
          @endphp
         <div class="form-group">
            <label for="category">subject</label>

              
            <select class="form-control" name="subject">
              <option selected disabled>Pick Up A Subject</option>
              {{-- <option value="Math2">Math(2)</option> --}}
              @foreach (explode(',',$hint->subjects) as $subject)
                 <option value="{{ $subject }}" {{$post->subject  === $subject ? "selected" : ''}}>{{  $subject }}</option>
              @endforeach
            </select>
        </div> 

        <div class="form-group">
            <label for="term">Term</label>
            <select class="form-control" name="term">
              <option selected disabled>Pick Up A Term</option>
                      <option value="first_term" {{$post->term  === "first_term" ? "selected" : ''}}>first term</option>
                      <option value="second_term" {{$post->term  === "second_term" ? "selected" : ''}}>second term</option>
            </select>
        </div>
        <div class="form-group">
            <label for="tags">Tag</label>
            <input type="text" name="tags" class="form-control" value="{{ implode(' ', $post->tags->pluck('name')->toArray()) }}">
        </div>

        <div class="form-group">
            <input type="hidden" name="_method" value="PUT">
            <input type="submit" name="submit" value="Release Post" class="btn btn-primary">
        </div>
  </form>
  
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('panel-heading')
    <p class="text-center">All Posts</p>
@endsection
@section('content')
<a href="{{ url('posts/create') }}">create</a>
    @if (count($posts) > 0)
        @foreach ($posts as $post)
          <h4 class="text-center">
            <strong>
              <a href="/posts/{{ $post->title }}">{{ $post->title }}</a>
              </strong>
          </h4>
        <a href="#" class="thumbnail">
            @php
                if(is_null($post->imagePath)){
                    $post_image = 'http://placehold.it/260x180';
                }else{
                    $post_image = 'images/' . $post->imagePath;
                }
            @endphp
            <img src="{{ $post_image }} " alt="">
        </a>
  
         <p class="text-center ">
          {{ str_limit($post->body,50) }}
        </p>
        <p>
            <a href="/posts/{{ $post->title }}"><small>Show more</small></a>
        </p>
         <p>
         <small> 
         <blockquote class="blockquote">

 <span class="label label-primary"> {{  $post->likes->count() }} {{ str_plural('like', $post->likes->count()) }}</span>

   @foreach ($post->likes as $userLiked)
      <span class="label label-info">{{$userLiked->user->username}}</span>
   @endforeach
            <i class="icon-user "></i> by <a href="#">{{ $post->admin->first_name }}</a> 
            | <i class="icon-calendar"></i> {{ $post->created_at}}
            | <i class="icon-comment"></i> <a href="#">{{ $post->comments->count() }} Comments</a>
            @if ($post->tags->count())
            | <i class="icon-tags"></i> Tags : 
            @foreach ($post->tags as $tag)<a href="/tags/{{$tag->name }}"><span class="label label-info">{{ $tag->name}}</span></a>
         </small>
          </blockquote>
            @endforeach
            @endif
        </p>
<hr> 
        @endforeach

    @else
        <div class="jumbotron">
           There is no posts to show  
        </div>
    @endif
@endsection