routes/web.php
<?php 
Route::get('/subject/{subject}/{category?}','PostController@listBySubject')->name('posts.category.index');
Route::redirect('/','/home');
Route::get('/home','HomeController@index')->name('home');
Route::get('archives/{year}/{month}','PostController@getByArchive')->name('archives');
Route::group(['namespace' => 'Auth'],function(){
	Route::group(['middleware' => 'guest'],function(){
		Route::get('/user/token','AuthTokenController@getToken')->name('token');
		Route::get('/token/resend','AuthTokenController@getResend')->name('resend-token');
		Route::post('/user/token','AuthTokenController@postToken')->name('token');
		Route::get('/register',[
			'uses' => 'RegisterController@getRegister',
			'as' => 'register'
		]);
		Route::post('/register',[
			'uses' => 'RegisterController@postRegister',
			'as' => 'register'
		]);
		Route::get('/login',[
			'uses' => 'LoginController@getLogin',
			'as' => 'login'
		]);
		Route::post('/login',[
			'uses' => 'LoginController@postLogin',
			'as' => 'login'
		]);
	
		

		Route::get('/activate/{email}/{token}','EmailActivationController@activateUser');
		Route::get('/resetpassword','ForgotPasswordController@getForgotPassword')->name('reset');
		Route::post('/resetpassword','ForgotPasswordController@postForgotPassword')->name('reset');
		Route::get('/reset/{email}/{token}','ResetPasswordController@getPasswordResetThroughEmail')->name('reset-password');
		Route::post('/reset-password','ResetPasswordController@postPasswordResetThroughEmail')->name('reset-password');
		Route::get('/resetBySecurityQuestion' , ['uses' => 'ResetPasswordController@getPasswordResetThroughQuestion','as' => 'reset.security']);
		Route::post('/resetBySecurityQuestion/stage1' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion1','as' => 'reset.security1']);
		Route::post('/resetBySecurityQuestion/stage2' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion2','as' => 'reset.security2']);
		Route::post('/resetBySecurityQuestion/stage3' , ['uses' => 'ResetPasswordController@postPasswordResetThroughQuestion3','as' => 'reset.security3']);
	});
});

// middleware
Route::group(['middleware' => 'user'],function(){
	Route::get('/dashboard','UserController@dashboard')->name('user.dashboard');
	Route::get('/profile/{username}',['uses' => 'UserController@getProfile','as' =>'profile']);
	Route::get('/profile/{username}/viewas',['uses' => 'UserController@getProfile','as' =>'profile.viewas']);
	Route::post('/profile',['uses' => 'UserController@postProfile','as' => 'profile']);
	Route::post('/rate/{username}',['uses' => 'UserController@postRate','as' => 'rating']);
		Route::post('/change-password',[
		'uses' => 'Auth\ChangePasswordController@postChangePassword',
		'as' => 'change-password'
	]);
	Route::get('/change-password',[
		'uses' => 'Auth\ChangePasswordController@getChangePassword',
		'as' => 'change-password'
	]);
	Route::post('logout',[
		'uses' => 'Auth\LoginController@logout',
		'as' => 'logout',
	]);	
	Route::post('/comments/{post}','CommentController@store')->name('comments.store');
	Route::put('/comments/{comment}','CommentController@update')->name('comments.update');
	Route::delete('/comments/{comment}','CommentController@destroy')->name('comments.destroy');
	Route::get('/replies/{reply}/{post}','RepliesController@edit')->name('replies.edit');
	Route::post('/replies/{comment}/{post}','RepliesController@store')->name('replies.store');
	Route::put('/replies/{reply}/{comment}/{post}','RepliesController@update')->name('replies.update');
	Route::delete('/replies/{reply}','RepliesController@destroy')->name('replies.destroy');
	Route::get('/comments/{comment}/{post}','CommentController@edit')->name('comments.edit');
	Route::post('/download/{post}','PostController@downloadFile')->name('posts.download');
	Route::get('/settings/twofactor','TwoFactorSettingsController@index')->name('2fa-settings');
	Route::put('/settings/twofactor','TwoFactorSettingsController@update');

	Route::post('/like/{type}/{id}',[
		'uses' => 'LikeController@like',
		'as'	=> 'like'
	]);
	Route::post('/dislike/{type}/{id}',[
		'uses' => 'LikeController@dislike',
		'as'	=> 'dislike'
	]);
	Route::post('/reset/like/{type}/{id}',[
		'uses' => 'LikeController@reset',
		'as'	=> 'reset-like'
	]);




	Route::get('/markAsRead',function(){
		\Sentinel::getUser()->unreadNotifications->markAsRead();
	});
});
	Route::group(['middleware' => 'admin'],function(){
		Route::view('/admin','admin.dashboard');
		Route::resource('/posts','PostController');
		Route::get('/upgrade','AdminController@listUsers')->name('list.users');
		Route::get('/downgrade','AdminController@listUsers');
		Route::post('/downgrade/{username}','AdminController@downgradeUser')->name('downgrade.users');
		Route::post('/upgrade/{username}','AdminController@upgradeUser')->name('upgrade.users');
		Route::get('/unapproved',['uses' => 'PostController@unApproved','as' => 'posts.unapproved']);
		Route::post('/posts/approve/{id}',['uses' => 'AdminController@approvePost','as' =>'posts.approve']);
		Route::resource('/tags','TagController');
		Route::get('/popular/tags','TagController@sortByPopularity');
		Route::put('/approve/comments/{comment}','CommentController@approveComment')->name('comments.approve');
		Route::put('/approve/replies/{reply}','RepliesController@approveReply')->name('replies.approve');
	});
	
	Route::get('/posts','PostController@index')->name('posts.index');
	Route::get('/posts/{post}','PostController@show')->name('posts.show');
	Route::get('/tags/{tag}','TagController@show')->name('tags.show');
Route::get('/comments/{comment}','CommentController@show')->name('comments.show');
Route::get('/replies/{reply}','RepliesController@show')->name('replies.show');
Route::get('/test',function(){
	dd(\App\Hint::menuElements());
	dd(array_merge(request()->all(),['reply' => Route::current()->parameter('reply')]));
	dd(request()->route('reply'));
	dd(Route::input('reply'));
	dd(request()->route()->parameter('reply'));
	$user = Sentinel::findById(10);
	$post = \App\Post::find(5);
	foreach ($post->RecentPostsDependingOnBranch($user->year,$user->department) as $posts) {
		dd($posts);
		foreach ($posts as $post) {
			echo $post->title . '<hr/>';
		}
	}
	//dd(\App\Post::find(5)->hints->first()->);	
});
?>

resources/views/admin/approve.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">	
	<title>Approve</title>
	<!-- Latest compiled and minified CSS & JS -->
	<link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<script src="https://code.jquery.com/jquery.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>
	<form action="{{ url('/admin') }}" method="POST" role="form">
		<legend>Form title</legend>
	{{ csrf_filed() }}
		<div class="form-group">
			<label for="">label</label>
			<input type="text" class="form-control" id="" placeholder="Input field">
		</div>
 		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
	<h5>list</h5>

</body>
</html>

resources/views/admin/dashboard.blade.php
@extends('layouts.master')
 
 <style >
 .glyphicon {
    line-height: 1.5 !important;
 }
 .btn-xs, .btn-group-xs > .btn {
    padding: 1px 5px;
    font-size: 12px;
    line-height: 1.5 !important;
    border-radius: 3px;
}
.table{
font-family: sans-serif !important;
font-size: 14px;
}
 </style>
 @section('content')
 {{--start- table --}} 
 <?php $posts = \App\Post::all()  ?>

<div class="row table"> 
        <div class="col-md-12">
        <h4>Bootstrap Snipp for Datatable</h4>
        <div class="table-responsive"> 
              <table id="mytable" class="table table-bordred table-striped">
	<thead>
		{{-- <th><input type="checkbox" id="checkall" /></th> --}}
		<th>ID</th>
		<th>title</th>
		<th>body</th>
		<th>department</th> 
		<th>approved</th>
		<th>Delete</th>
	</thead>
    <tbody>
     @foreach ($posts as  $post)
    <tr>
    {{-- <td><input type="checkbox" class="checkthis" /></td> --}}
    <td>{{ $post->id }}</td>
    <td> {{ str_limit($post->title, 10) }}</td>
    <td> {{ str_limit($post->body, 20) }}</td> 
    <td> {{ str_limit(str_replace("_", " ", $post->department), 20) }}</td>  
 {!! $post->approved ==0 ? " <td><span class=\"label label-warning\">Pending</span></td> " : "<td> <span class=\"label label-success\">approved</span>
</td>"  !!}

    <td>
	    <p data-placement="top" data-toggle="tooltip" title="approved">
        	    <button class="btn btn-primary btn-xs" data-title="approved" data-toggle="modal" data-target="#approved" >
        	       <span class="glyphicon glyphicon-pencil"></span>
        	    </button>
      </p>
    </td>
    <td>
        <p data-placement="top" data-toggle="tooltip" title="Delete">
            <button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" >
              <span class="glyphicon glyphicon-trash"></span>
            </button>
        </p>
    </td>
    </tr>
 @endforeach
 
       </tbody>
        
</table>

<div class="clearfix"></div>
<ul class="pagination pull-right">
  <li class="disabled">
  	<a href="#">
  	<span class="glyphicon glyphicon-chevron-left"></span>
  	</a>
</li>
  <li class="active"><a href="#">1</a></li>
  <li><a href="#">2</a></li>
  <li><a href="#"><span class="glyphicon glyphicon-chevron-right"></span></a></li>
</ul> 
            </div>
        </div>
</div> 

<div class="modal fade" id="approved" tabindex="-1" role="dialog" aria-labelledby="approved" aria-hidden="true">
      <div class="modal-dialog">
    <div class="modal-content">
          <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">approved Your Detail</h4>


      </div>
          <div class="modal-footer ">
            {{--  --}}
            <a  class="dropdown-item" href="{{ route('posts.approve',$post->id) }}" onclick="event.preventDefault(); document.getElementById('form-control').submit();">
                   <button type="button" class="btn btn-success" ><span class="glyphicon glyphicon-ok-sign"></span>approved</button>
            </a>
            <form id="form-control" action="{{ route('posts.approve',$post->id) }}" method="POST" style="display: none;">
               {{ csrf_field() }}
            </form>
            {{--  --}}
        <button type="button" class="btn btn-danger" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span>un approve</button>
          <a  href="{{ route('posts.edit',$post->title) }}"> <button type="button" class="btn btn-info"><span class="glyphicon glyphicon-remove"></span>Edit</button></a>

       </div>
        </div>

    <!-- /.modal-content --> 
  </div>
      <!-- /.modal-dialog --> 
    </div> 

    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="approved" aria-hidden="true">
      <div class="modal-dialog">
    <div class="modal-content">
          <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">Delete this entry</h4>
      </div>
          <div class="modal-body">

       <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Are you sure you want to delete this Record?</div>
       
      </div>
        <div class="modal-footer ">
 {{--  --}}
  <a  class="dropdown-item" href="{{ route('posts.destroy',$post->title) }}" onclick="event.preventDefault(); document.getElementById('destroy-form').submit();">
        <button type="button" class="btn btn-success" ><span class="glyphicon glyphicon-ok-sign"></span>Yes</button>
  </a>
  <form id="destroy-form" action="{{ route('posts.destroy',$post->title) }}" method="POST" style="display: none;">
     {{ csrf_field() }}
     {{ method_field('DELETE')}}
  </form>
 {{--  --}} 
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
      </div>
        </div>
    <!-- /.modal-content --> 
  </div>
      <!-- /.modal-dialog --> 
    </div> 
{{--end table --}} 
@endsection

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
<script >
$(document).ready(function(){$("#mytable #checkall").click(function () {
        if ($("#mytable #checkall").is(':checked')) {
            $("#mytable input[type=checkbox]").each(function () {
                $(this).prop("checked", true);
            });
        } else {
            $("#mytable input[type=checkbox]").each(function () {
                $(this).prop("checked", false);
            });
        }
    });
    $("[data-toggle=tooltip]").tooltip();
}); 

$(function(){
       $('#button').click(function() {
            $.ajax({
                url: 'admin/{id}',
                type: 'post',
                data: { id: 1 },
                success: function(response)
                {
                
                  alert('response');
                }
            });
       });
    });   
</script>

resources/views/admin/downgrade.blade.php
@extends('layouts.app')

@section('panel-heading')
	Upgrade Users
@endsection
@section('content')
	<ul class="list-group">
		@if ($users != NULL)
			{{-- expr --}}
		@foreach ($users as $user)
			<li class="list-group-item" style="height:350px">
				{{ $user->username }} : {{ $user->roles->first()->name }} <br />
				Real Permissions : 
				<ul class="list-group">
					@foreach ($user->roles->first()->permissions as $permission => $value)
						@if ($value)
							
						<li class="list-group-item"> {{$permission .'=>' . 'true'}}</li>
						@else
							<li class="list-group-item"> {{$permission .'=>' . 'false'}}</li>

						@endif
					@endforeach
					@if($user->permissions != NULL)
						Updated Permissions : <br />
						@foreach ($user->permissions as $permission => $value)
						@if ($value)
						<li class="list-group-item"> {{$permission .'=>' . 'true'}}</li>
						@else
							<li class="list-group-item"> {{$permission .'=>' . 'false'}}</li>

						@endif
						@endforeach
					@endif
				</ul>
				
				<div class="pull-right">
					<form action="{{ route('downgrade.users',$user->username) }}" method="POST">
						{{csrf_field()}}
						Show :<input type="checkbox" name="list[]" value="show">
						Create : <input type="checkbox" name="list[]" value="create">
						Edit :<input type="checkbox" name="list[]" value="edit">
						Delete :<input type="checkbox" name="list[]" value="delete">
						Approve :<input type="checkbox" name="list[]" value="approve">
						Permission Level
						<select name="permission_level" class="form-control">
							<option value="admin">Adminstrator</option>	
							<option value="moderator">Moderator</option>	
							<option value="user">Normal User</option>	
						</select>
						<input type="submit" value="Downgrade User">
					</form>
					
				</div>
			</li>
		@endforeach
		@endif
	</ul>
@endsection

resources/views/admin/upgrade.blade.php
@extends('layouts.app')

@section('panel-heading')
	Upgrade Users
@endsection
@section('content')
	<ul class="list-group">
		@if ($users != NULL)
			{{-- expr --}}
		@foreach ($users as $user)
			<li class="list-group-item" style="height:350px">
				{{ $user->username }} : {{ $user->roles->first()->name }} <br />
				Real Permissions : 
				<ul class="list-group">
					@foreach ($user->roles->first()->permissions as $permission => $value)
						@if ($value)
							
						<li class="list-group-item"> {{$permission .'=>' . 'true'}}</li>
						@else
							<li class="list-group-item"> {{$permission .'=>' . 'false'}}</li>

						@endif
					@endforeach
					@if($user->permissions != NULL)
						Updated Permissions : <br />
						@foreach ($user->permissions as $permission => $value)
						@if ($value)
						<li class="list-group-item"> {{$permission .'=>' . 'true'}}</li>
						@else
							<li class="list-group-item"> {{$permission .'=>' . 'false'}}</li>

						@endif
						@endforeach
					@endif
				</ul>
				
				<div class="pull-right">
					<form action="{{ route('upgrade.users',$user->username) }}" method="POST">
						{{csrf_field()}}
						Show :<input type="checkbox" name="list[]" value="show">
						Create : <input type="checkbox" name="list[]" value="create">
						Edit :<input type="checkbox" name="list[]" value="edit">
						Delete :<input type="checkbox" name="list[]" value="delete">
						Approve :<input type="checkbox" name="list[]" value="approve">
						Permission Level
						<select name="permission_level" class="form-control">
							<option value="admin">Adminstrator</option>	
							<option value="moderator">Moderator</option>	
							<option value="user">Normal User</option>	
						</select>
						<input type="submit" value="Upgrade User">
					</form>
					
				</div>
			</li>
		@endforeach
		@else
			<p class="text-center">No users to upgrade</p>
		@endif
	</ul>
@endsection